name: gotth-app
component: application

# Default values for my homelab
replicaCount: 3

image:
  repository: ghcr.io/dobsondev/repo-name
  tag: v0.0.1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000
  # Example of using NodePort instead of ClusterIP:
  # type: NodePort
  # port: 3000
  # nodePort: 30080  # Specify a nodePort between 30000-32767

ingress:
  enabled: false
  host: example.homelab.dobson.dev

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Pod config mapping
configMap: {}
# configMap:
#   key: value
#   another-key: another-value

# Pod environment variables
env: []
# env:
# - name: APP_ENV
#   value: production