apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homelab-dobson-dev-production
  namespace: default
spec:
  secretName: homelab-dobson-dev-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.homelab.dobson.dev"
  dnsNames:
  - "homelab.dobson.dev"
  - "*.homelab.dobson.dev"