apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k3s-dobson-dev-staging
  namespace: default
spec:
  secretName: k3s-dobson-dev-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.k3s.dobson.dev"
  dnsNames:
  - "k3s.dobson.dev"
  - "*.k3s.dobson.dev"