name: dobsondev-homelab

replicaCount: 2

image:
  repository: ghcr.io/dobsondev/repo-name
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 3000
  nodePort: 30080  # Specify a nodePort between 30000-32767

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi