apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  # Item must have fields named exactly `admin-user` and `admin-password`
  # to match kube-prometheus-stack.yml's grafana.admin.userKey/passwordKey.
  itemPath: "vaults/k3s-cluster/items/emciregqhdgf5szbq3opuzmej4"
