apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gotth-stack
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/dobsondev/homelab.git
    path: argocd/helm/gotth-app
    targetRevision: main
    helm:
      valueFiles:
        # Note, this is relative path to the chart above (argocd/helm)
        - ../apps/values/gotth-stack.yml
  destination:
    namespace: gotth-stack
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true