name: go-logging-example-app
component: application
replicaCount: 1
image:
  repository: ghcr.io/dobsondev/go-logging-example-app
  tag: v0.2.0
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: true
  host: go-logging-example-app.homelab.dobson.dev
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi
env:
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: "tempo.monitoring.svc.cluster.local:4318"
  - name: SERVICE_NAME
    value: "go-logging-example-app"
