apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: email@example.com # Replace with your email
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - dns01:
        cloudflare:
          email: email@example.com # Replace with your email
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: cloudflare-token
      selector:
        dnsZones:
        - "example.com" # Replace with your domain