apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: alex@dobsondev.com
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
    - dns01:
        cloudflare:
          email: alex@dobsondev.com
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: cloudflare-token
      selector:
        dnsZones:
        - "dobson.dev"