apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  trigger.on-sync-succeeded: |
    - when: app.status.operationState.phase in ['Succeeded']
      send: [grafana-deployment-annotation]

  template.grafana-deployment-annotation: |
    webhook:
      grafana:
        method: POST
        path: /api/annotations
        body: |
          {
            "text": "Deployed {{.app.metadata.name}} → {{.app.status.summary.images}}",
            "tags": ["deployment", "{{.app.metadata.name}}"],
            "time": {{mul (now | unixEpoch) 1000}}
          }

  service.webhook.grafana: |
    url: http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local:80
    headers:
    - name: Authorization
      value: Bearer $grafana_api_token
    - name: Content-Type
      value: application/json
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: argocd-notifications-secret
  namespace: argocd
spec:
  itemPath: "vaults/Homelab/items/wz7gru43u5p76aa7mpgxqo4lrq"
