apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-logging-example-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.grafana: ""
spec:
  project: default
  source:
    repoURL: https://github.com/dobsondev/homelab.git
    path: argocd/helm/charts/basic-service
    targetRevision: main
    helm:
      valueFiles:
      # Note, this is relative path to the chart above (argocd/helm/<chart>)
      - ../../values/go-logging-example-app.yml
  destination:
    namespace: go-logging-example-app
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
