apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homeassistant
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - chart: home-assistant
      repoURL: https://pajikos.github.io/home-assistant-helm-chart/
      targetRevision: 0.3.23
  destination:
    server: https://kubernetes.default.svc
    namespace: home-assistant
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-assistant-frontend-ingress
  namespace: home-assistant
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  tls:
  - hosts:
    - home-assistant.homelab.dobson.dev
    secretName: home-assistant-tls
  rules:
  - host: home-assistant.homelab.dobson.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: homeassistant-home-assistant
            port:
              number: 8080