apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
  labels:
    app.kubernetes.io/name: {{ .Values.name }}-service
    app.kubernetes.io/instance: {{ .Values.name }}-service-{{ .Values.image.tag }}
    app.kubernetes.io/version: {{ .Values.image.tag }}
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: {{ .Values.name }}
    app.kubernetes.io/managed-by: Helm
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app.kubernetes.io/name: {{ .Values.name }}-pod
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: {{ .Values.name }}