apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-deployment
  labels:
    app.kubernetes.io/name: {{ .Values.name }}-deployment
    app.kubernetes.io/instance: {{ .Values.name }}-deployment-{{ .Values.image.tag }}
    app.kubernetes.io/version: {{ .Values.image.tag }}
    app.kubernetes.io/component: {{ .Values.component }}
    app.kubernetes.io/part-of: {{ .Values.name }}
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.name }}-pod
      app.kubernetes.io/instance: {{ .Values.name }}-pod-{{ .Values.image.tag }}
      app.kubernetes.io/version: {{ .Values.image.tag }}
      app.kubernetes.io/component: {{ .Values.component }}
      app.kubernetes.io/part-of: {{ .Values.name }}
      app.kubernetes.io/managed-by: Helm
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.name }}-pod
        app.kubernetes.io/instance: {{ .Values.name }}-pod-{{ .Values.image.tag }}
        app.kubernetes.io/version: {{ .Values.image.tag }}
        app.kubernetes.io/component: {{ .Values.component }}
        app.kubernetes.io/part-of: {{ .Values.name }}
        app.kubernetes.io/managed-by: Helm
    spec:
      containers:
        - name: {{ .Values.name }}-container
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.env }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          {{- end }}