name: CI

#
# This workflow runs on pull requests to the main branch and performs the 
# following checks:
# 1. Lints all YAML files in the argocd/ directory using yamllint
# 2. Lints any custom Helm Charts:
#    - Basic Service Helm Chart located at argocd/helm/charts/basic-service
#

on:
  pull_request:
    branches:
      - main

jobs:
  lint-yaml:
    name: Lint YAML Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint YAML Files (Relaxed Rules)
        run: yamllint -d relaxed argocd/**/*.yml

  lint-custom-helm-charts:
    name: Lint Custom Helm Charts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chart-name:
          - basic-service
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v5.0.0

      - name: Lint Helm Chart
        run: helm lint argocd/helm/charts/${{ matrix.chart-name }}